In [190]:
import numpy as np

In [191]:
x=np.array([1,2,3,4,5])
x.dtype,x.size,x.shape

x2=np.array([7,4,2,2,5])

In [192]:
y=np.array([
    [2,3,4,5,6],[9,8,7,6,8]
])
y.dtype,y.size,y.shape
y1=np.array([1,2,3,4,5])

y+y1

array([[ 3,  5,  7,  9, 11],
       [10, 10, 10, 10, 13]])

In [193]:
y+3
x+x2 # adding the elements to the index and it does not work if the shapes are same

array([ 8,  6,  5,  6, 10])

In [194]:
z1=np.array([
    [
        [2,1,3,4],
        [2,3,5,6],
        [7,5,4,3]
    ],
    [
        [-3,1,3,4],
        [2,-1,5,6],
        [7,5,4,3]
    ]
])
z2=np.array([
    [1,2,3,4]
])
z1+z2
z3=np.array([1])
z1+z3
z4=np.array([
    [1,8,4,2],
    [1,9,4,2],
    [1,8,4,2]
])
z1+z4
z5=np.array([-1,6,4,2])
z1+z5





array([[[ 1,  7,  7,  6],
        [ 1,  9,  9,  8],
        [ 6, 11,  8,  5]],

       [[-4,  7,  7,  6],
        [ 1,  5,  9,  8],
        [ 6, 11,  8,  5]]])

In [195]:
# create four dimenstonal array

z1=np.array([
    [
        [
        [2,1,3,4,3],
        [2,3,5,6,7],
        [7,5,4,3,9]
        ]
    ],
    [
        [
        [2,1,3,4,0],
        [2,3,5,6,2],
        [7,5,4,3,7]
        ]
    ]
])
z1.shape


(2, 1, 3, 5)