In [72]:
import numpy as np
x=np.zeros((2,3,4)) # float data type
x.dtype=int
print(x)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [73]:
y=np.full((2,3,4),5) # float data type
y[0][1][2]=3

print(y)

[[[5 5 5 5]
  [5 5 3 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [74]:
z1=np.array([
    [
        [2,1,3,4],
        [2,3,5,6],
        [7,5,4,3]
    ],
    [
        [-3,1,3,4],
        [2,-1,5,6],
        [7,5,4,3]
    ]
])
print(z1.shape)

z1+np.ones((1,3,1))

(2, 3, 4)


array([[[ 3.,  2.,  4.,  5.],
        [ 3.,  4.,  6.,  7.],
        [ 8.,  6.,  5.,  4.]],

       [[-2.,  2.,  4.,  5.],
        [ 3.,  0.,  6.,  7.],
        [ 8.,  6.,  5.,  4.]]])

In [75]:
x=np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

In [76]:
# np.random.randn(10)  # submodule for numpy
(np.random.random((2,4,2))*10).round()


array([[[ 6., 10.],
        [ 5.,  8.],
        [ 0.,  8.],
        [ 1.,  4.]],

       [[ 7.,  8.],
        [ 6.,  1.],
        [ 4.,  2.],
        [ 8.,  2.]]])

In [77]:
x=((np.random.random((2,4,2))*200)-100) # from -100 to 100 random values
x=np.array(x,dtype=int)
x.max(), x.min(),x.sum(),x.mean()
print(x)

[[[-97 -16]
  [-88 -72]
  [ 96  52]
  [ 82 -72]]

 [[ 95 -14]
  [ -9  72]
  [-61  44]
  [ 67  38]]]


In [81]:
o = np.array([
    [
        [2,1,5,3],
        [1,2,3,5],
        [9,5,0,3]
    ],
    [
        [2,-1,3,3],
        [1,5,3,2],
        [4,3,0,5]
    ]
])

o[:,0:2,0:2]

# generate 3 random +ve integers in range [2,6), then use them as shape to create a 3d array,
# from that 3d array print out the last 2 indexes of each of the sub lists

array([[[ 2,  1],
        [ 1,  2]],

       [[ 2, -1],
        [ 1,  5]]])

In [108]:
x=(np.random.random((2,3,3))*20)-6
x

array([[[11.7750892 ,  2.39810487,  7.84270239],
        [-1.71752946,  6.7719998 , 13.41131138],
        [ 8.17855941, -3.3533934 , 10.84038616]],

       [[12.20521813, -2.13181088,  6.67311602],
        [ 2.67833181,  8.81261144,  9.45872618],
        [ 1.91073959, -3.6959193 , -3.41252482]]])

In [ ]:
y=(np.random.random((3,3,4))*4+2).round()

